export const LOG_EVENTS = {
  // Server events
  SERVER_STARTED: "SERVER_STARTED",
  SERVER_SHUTDOWN: "SERVER_SHUTDOWN",
  SERVER_CLOSED: "SERVER_CLOSED",
  SERVER_ERROR: "SERVER_ERROR",

  // Binance WebSocket events
  BINANCE_STREAM_STARTED: "BINANCE_STREAM_STARTED",
  BINANCE_STREAM_CONNECTED: "BINANCE_STREAM_CONNECTED",
  BINANCE_STREAM_DISCONNECTED: "BINANCE_STREAM_DISCONNECTED",
  BINANCE_STREAM_ERROR: "BINANCE_STREAM_ERROR",
  BINANCE_STREAM_SUBSCRIBED: "BINANCE_STREAM_SUBSCRIBED",
  BINANCE_STREAM_RECONNECTING: "BINANCE_STREAM_RECONNECTING",
  BINANCE_STREAM_RECONNECT_FAILED: "BINANCE_STREAM_RECONNECT_FAILED",
  BINANCE_STREAM_STOPPED: "BINANCE_STREAM_STOPPED",
  BINANCE_MESSAGE_PARSE_ERROR: "BINANCE_MESSAGE_PARSE_ERROR",

  // API events
  API_REQUEST: "API_REQUEST",
  API_RESPONSE: "API_RESPONSE",
  API_ERROR: "API_ERROR",
  CRYPTO_PRICES_FETCHED: "CRYPTO_PRICES_FETCHED",
  CRYPTO_PRICES_ERROR: "CRYPTO_PRICES_ERROR",

  // Validation events
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

